export const saveDataRaw = 
`
{
    "saveFormatVersion":1,
    "level":"Home",
    "world":{
        "tiles":[
            {
                "type":"plane",
                "spritesheets":[
                    "textures/terrain/grassdirt-big.png"
                ],
                "width":"50",
                "height":"50",
                "position":{
                    "x":0,
                    "y":0,
                    "z":0
                }
            },
            {
                "type":"DialogTile",
                "message":"What in the god damn? Now it's time for you to die!",
                "buttons":[
                    {
                        "message":"Oh fuck!"
                    }
                ],
                "position":{
                    "x":5,
                    "y":5
                }
            }
        ],
        "entities":[

        ]
    },
    "player":{
        "position":{
            "x":0,
            "y":0,
            "z":0
        },
        "rotation":{
            "x":0,
            "y":0,
            "z":0
        }
    }
}
`;